// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3jZKt9lSmfqb8xt7Oi-FvTK8veZqV_M',
    appId: '1:913614488724:web:f7beb0cb199ff7c092a081',
    messagingSenderId: '913614488724',
    projectId: 'mynotes-2d6f9',
    authDomain: 'mynotes-2d6f9.firebaseapp.com',
    storageBucket: 'mynotes-2d6f9.firebasestorage.app',
    measurementId: 'G-8N31FX3L3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUXH2r9kWkFRw7grHlWA6fbwQo_TfCH_E',
    appId: '1:913614488724:android:37f0dd14f87c267f92a081',
    messagingSenderId: '913614488724',
    projectId: 'mynotes-2d6f9',
    storageBucket: 'mynotes-2d6f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQjwfPlXWtgq4FwBRR0m0-LodV6CSGY0',
    appId: '1:913614488724:ios:97057436bf5e22d992a081',
    messagingSenderId: '913614488724',
    projectId: 'mynotes-2d6f9',
    storageBucket: 'mynotes-2d6f9.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQjwfPlXWtgq4FwBRR0m0-LodV6CSGY0',
    appId: '1:913614488724:ios:97057436bf5e22d992a081',
    messagingSenderId: '913614488724',
    projectId: 'mynotes-2d6f9',
    storageBucket: 'mynotes-2d6f9.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb3jZKt9lSmfqb8xt7Oi-FvTK8veZqV_M',
    appId: '1:913614488724:web:029d2792c4caf4e692a081',
    messagingSenderId: '913614488724',
    projectId: 'mynotes-2d6f9',
    authDomain: 'mynotes-2d6f9.firebaseapp.com',
    storageBucket: 'mynotes-2d6f9.firebasestorage.app',
    measurementId: 'G-8KPL7H2H26',
  );
}
